import Foundation

let imagePresets: [ImagePreset] = [
    ImagePreset(image: "https://sdbooth2-production.s3.amazonaws.com/hckjpa47pyz2cd9ufakmqafxi1hu", systemPrompt: "A sks \(Consts.shared.selectedGender ?? "") stands confidently against a softly blurred, clean background. His expression is warm and approachable, radiating authenticity and charm. He is dressed in a modern, stylish outfit — a crisp shirt layered with a tailored blazer — perfect for a dating profile. Natural, soft lighting highlights the gentle contours of his face, bringing out warm skin tones and expressive eyes. The portrait has a professional yet relaxed tone, designed to convey confidence and genuine personality.", category: .headshots),
    ImagePreset(image: "https://sdbooth2-production.s3.amazonaws.com/rz1vx1p2o9n3h21yo5xkv5tdmmk8", systemPrompt: "A sks \(Consts.shared.selectedGender ?? "") stands confidently against a softly blurred, clean background. His expression is warm and approachable, radiating authenticity and charm. He is dressed in a modern, stylish outfit — a crisp shirt layered with a tailored blazer — perfect for a dating profile. Natural, soft lighting highlights the gentle contours of his face, bringing out warm skin tones and expressive eyes. The portrait has a professional yet relaxed tone, designed to convey confidence and genuine personality.", category: .headshots),
    ImagePreset(image: "https://sdbooth2-production.s3.amazonaws.com/vlde9w180cfgnhlg9m2rmsgc7zgp", systemPrompt: "A sks \(Consts.shared.selectedGender ?? "") is captured in a professional corporate headshot, styled in the realistic and polished ukj style. Standing confidently in a modern office environment with a softly blurred background, this \(Consts.shared.selectedGender ?? "") wears a crisp white shirt and a navy blue blazer, radiating professionalism and approachability. Soft natural lighting enhances the sharp, realistic details, presenting a clean, executive look ideal for professional use.", category: .headshots),
    ImagePreset(image: "https://sdbooth2-production.s3.amazonaws.com/hiwd8kxrhfnsoxhgdsa80kxsjr1u", systemPrompt: "A sks \(Consts.shared.selectedGender ?? "") stands confidently in a crisp, tailored suit against a clean, minimalist background, styled for a sophisticated corporate headshot. The scene emphasizes professionalism and elegance, with subtle lighting that enhances the defined facial structure and thoughtful gaze. The overall image feels polished and refined, presenting a modern, powerful presence suitable for high-end executive or business-focused visuals.", category: .headshots),
    ImagePreset(image: "https://sdbooth2-production.s3.amazonaws.com/6pqj5ev2vu32q48p340r6h5hy35b", systemPrompt: "A sks \(Consts.shared.selectedGender ?? "") is portrayed in a stylish office profile setting, wearing a clean white shirt with no neckline. Flawless makeup complements the overall look, with a warm, confident expression directed slightly away from the camera. A gold ring adorns one finger and striking red nails add a bold accent. The background features a sophisticated lawyer's office with an intimate, elegant atmosphere, completing a polished and professional scene ideal for a modern profile image.", category: .headshots),
    ImagePreset(image: "https://sdbooth2-production.s3.amazonaws.com/3qu1pmjyy41kyjgdcqdr6e50kpw2", systemPrompt: "A sks \(Consts.shared.selectedGender ?? "") is captured in a professional three-quarter view, styled as a Sequoia Capital partner. Wearing a tailored blazer with a structured silhouette, this \(Consts.shared.selectedGender ?? "") exudes authority, expertise, and modern executive presence. The expression and posture convey a balance of confidence and approachability. A subdued, elegant background ensures the focus remains entirely on this accomplished figure, reinforcing the image of a respected leader in the industry.", category: .headshots),
    
    ImagePreset(image: "https://sdbooth2-production.s3.amazonaws.com/5tfhizqkqiuo1fsivyywv6sqaydf", systemPrompt: "A sks \(Consts.shared.selectedGender ?? "") stands confidently beside a sleek BMW iX, styled as a modern business figure with a photographer's creative edge. Wearing a smart, contemporary outfit, this \(Consts.shared.selectedGender ?? "") blends corporate sophistication with artistic flair. The scene is set outdoors or near a high-end commercial building, with clean lines and a subtle backdrop that enhances the professional tone. The overall mood conveys success, innovation, and a lifestyle rooted in ambition and style.", category: .business),
    ImagePreset(image: "https://sdbooth2-production.s3.amazonaws.com/vs4na33lgh8gena0eqzb7z3gkynj", systemPrompt: "A sks \(Consts.shared.selectedGender ?? "") stands tall in a stylish, tailored suit, bathed in the warm glow of a setting sun. The golden light casts a timeless atmosphere across the scene, enhancing the elegant lines of the outfit and the strong posture of this successful entrepreneur. The surrounding environment feels expansive and cinematic, reinforcing a sense of grandeur, purpose, and personal achievement.", category: .business),
    ImagePreset(image: "https://sdbooth2-production.s3.amazonaws.com/xhhi290cu5e3juoxrqd45fqexdco", systemPrompt: "A sks \(Consts.shared.selectedGender ?? "") is captured in a sharp, high-resolution photographic portrait, styled with clean composition and natural expression. The subject appears grounded and present, with subtle lighting that brings out detailed textures and realistic skin tones. The setting is minimal, allowing focus to remain entirely on the face and upper body, conveying clarity, confidence, and authenticity. This portrait is ideal for professional use, personal branding, or editorial-style features.", category: .business),
    ImagePreset(image: "https://sdbooth2-production.s3.amazonaws.com/pvaqej7nximyz0t5uipsvaxix8qd", systemPrompt: "A sks \(Consts.shared.selectedGender ?? "") stands confidently beside a sleek BMW iX, styled as a modern business figure with a photographer's creative edge. Wearing a smart, contemporary outfit, this \(Consts.shared.selectedGender ?? "") blends corporate sophistication with artistic flair. The scene is set outdoors or near a high-end commercial building, with clean lines and a subtle backdrop that enhances the professional tone. The overall mood conveys success, innovation, and a lifestyle rooted in ambition and style.", category: .business),
    ImagePreset(image: "https://sdbooth2-production.s3.amazonaws.com/ungyjsk0gd5bsei5xyqgtj0lff74", systemPrompt: "A sks \(Consts.shared.selectedGender ?? "") stands confidently beside a sleek BMW iX, styled as a modern business figure with a photographer's creative edge. Wearing a smart, contemporary outfit, this \(Consts.shared.selectedGender ?? "") blends corporate sophistication with artistic flair. The scene is set outdoors or near a high-end commercial building, with clean lines and a subtle backdrop that enhances the professional tone. The overall mood conveys success, innovation, and a lifestyle rooted in ambition and style.", category: .business),
    ImagePreset(image: "https://sdbooth2-production.s3.amazonaws.com/lwucq7xrx4sk91xt4bge9p93h1at", systemPrompt: "A sks \(Consts.shared.selectedGender ?? "") stands confidently beside a sleek BMW iX, styled as a modern business figure with a photographer's creative edge. Wearing a smart, contemporary outfit, this \(Consts.shared.selectedGender ?? "") blends corporate sophistication with artistic flair. The scene is set outdoors or near a high-end commercial building, with clean lines and a subtle backdrop that enhances the professional tone. The overall mood conveys success, innovation, and a lifestyle rooted in ambition and style.", category: .business),
    
    ImagePreset(image: "https://sdbooth2-production.s3.amazonaws.com/k3h5ma6renbngbvwhvdgu0c52s6h", systemPrompt: "A sks \(Consts.shared.selectedGender ?? "") appears in a surreal, visually captivating portrait with a vintage aesthetic. Wearing oversized steampunk-style goggles that reflect an underwater world, this \(Consts.shared.selectedGender ?? "") seems to peer into a dreamlike, submerged reality. Gold and silver fish swim gracefully through the scene, with some appearing to pass through the goggles themselves. Styled with dark brown hair in a classic retro bob, bold red lips, and a floral-patterned blouse, the look evokes both fantasy and timeless charm. The soft aquatic background, with flowing plants and subtle water ripples, completes a scene blending surrealism, vintage portraiture, and imaginative storytelling.", category: .cartoon),
    ImagePreset(image: "https://sdbooth2-production.s3.amazonaws.com/ag7mmcsckc6zs5lz1n6zzpwxuh6h", systemPrompt: "A sks \(Consts.shared.selectedGender ?? "") appears in a surreal and whimsical portrait, styled with vibrant orange hair gathered into two symmetrical buns. Wearing round, oversized sunglasses that reflect a lush green meadow filled with blooming white flowers, this \(Consts.shared.selectedGender ?? "") becomes the focal point of a dreamy, nature-inspired scene. The slightly parted lips add a touch of softness and curiosity, while the composition radiates lightness and imagination. The overall aesthetic blends fantasy, fashion, and floral elements into a vibrant, daydream-like visual.", category: .cartoon),
    ImagePreset(image: "https://sdbooth2-production.s3.amazonaws.com/afu2ba6vx63s9v0v4odpgl0gikpt", systemPrompt: "A sks \(Consts.shared.selectedGender ?? "") appears in a surreal, visually captivating portrait with a vintage aesthetic. Wearing oversized steampunk-style goggles that reflect an underwater world, this \(Consts.shared.selectedGender ?? "") seems to peer into a dreamlike, submerged reality. Gold and silver fish swim gracefully through the scene, with some appearing to pass through the goggles themselves. Styled with dark brown hair in a classic retro bob, bold red lips, and a floral-patterned blouse, the look evokes both fantasy and timeless charm. The soft aquatic background, with flowing plants and subtle water ripples, completes a scene blending surrealism, vintage portraiture, and imaginative storytelling.", category: .cartoon),
    ImagePreset(image: "https://sdbooth2-production.s3.amazonaws.com/wj92daw33n3v6p7eifazdhjqywyt", systemPrompt: "A sks \(Consts.shared.selectedGender ?? "") appears in a surreal and whimsical portrait, styled with vibrant orange hair gathered into two symmetrical buns. Wearing round, oversized sunglasses that reflect a lush green meadow filled with blooming white flowers, this \(Consts.shared.selectedGender ?? "") becomes the focal point of a dreamy, nature-inspired scene. The slightly parted lips add a touch of softness and curiosity, while the composition radiates lightness and imagination. The overall aesthetic blends fantasy, fashion, and floral elements into a vibrant, daydream-like visual.", category: .cartoon),
    ImagePreset(image: "https://sdbooth2-production.s3.amazonaws.com/xe50gxovtx7uwe8zsstdpn3vjson", systemPrompt: "A sks \(Consts.shared.selectedGender ?? "") appears in a surreal, visually captivating portrait with a vintage aesthetic. Wearing oversized steampunk-style goggles that reflect an underwater world, this \(Consts.shared.selectedGender ?? "") seems to peer into a dreamlike, submerged reality. Gold and silver fish swim gracefully through the scene, with some appearing to pass through the goggles themselves. Styled with dark brown hair in a classic retro bob, bold red lips, and a floral-patterned blouse, the look evokes both fantasy and timeless charm. The soft aquatic background, with flowing plants and subtle water ripples, completes a scene blending surrealism, vintage portraiture, and imaginative storytelling.", category: .cartoon),
    
    ImagePreset(image: "https://sdbooth2-production.s3.amazonaws.com/wwxe8bk4zs8joyqs4lv0mo9iypr7", systemPrompt: "A dark sks \(Consts.shared.selectedGender ?? "") appears as a rapper in a gritty horror manga-inspired multi-panel scene. Styled in intense shades of red without black and white, the artwork captures a violent gang war unfolding with dramatic energy and expressive line work. Urban backdrops are fragmented across panels, blending chaos and action in a comic book format. The overall aesthetic is aggressive, surreal, and cinematic, evoking fear, adrenaline, and raw power through stylized manga visuals.", category: .rapper),
    ImagePreset(image: "https://sdbooth2-production.s3.amazonaws.com/r6l5ct8lktv0vf2x2k0hiavq8aye", systemPrompt: "A dark sks \(Consts.shared.selectedGender ?? "") appears as a rapper in a gritty horror manga-inspired multi-panel scene. Styled in intense shades of red without black and white, the artwork captures a violent gang war unfolding with dramatic energy and expressive line work. Urban backdrops are fragmented across panels, blending chaos and action in a comic book format. The overall aesthetic is aggressive, surreal, and cinematic, evoking fear, adrenaline, and raw power through stylized manga visuals.", category: .rapper),
    ImagePreset(image: "https://sdbooth2-production.s3.amazonaws.com/wgipbtbqtvyu6h2deylm155f75dk", systemPrompt: "A dark sks \(Consts.shared.selectedGender ?? "") appears as a rapper in a gritty horror manga-inspired multi-panel scene. Styled in intense shades of red without black and white, the artwork captures a violent gang war unfolding with dramatic energy and expressive line work. Urban backdrops are fragmented across panels, blending chaos and action in a comic book format. The overall aesthetic is aggressive, surreal, and cinematic, evoking fear, adrenaline, and raw power through stylized manga visuals.", category: .rapper),
    ImagePreset(image: "https://sdbooth2-production.s3.amazonaws.com/qazq3lj4odpv4m35fxwy3jraxlf1", systemPrompt: "A dark sks \(Consts.shared.selectedGender ?? "") appears as a rapper in a gritty horror manga-inspired multi-panel scene. Styled in intense shades of red without black and white, the artwork captures a violent gang war unfolding with dramatic energy and expressive line work. Urban backdrops are fragmented across panels, blending chaos and action in a comic book format. The overall aesthetic is aggressive, surreal, and cinematic, evoking fear, adrenaline, and raw power through stylized manga visuals.", category: .rapper),
    
    ImagePreset(image: "https://sdbooth2-production.s3.amazonaws.com/ynmp8t51g08osy075mm75jz2plw2", systemPrompt: "A sks \(Consts.shared.selectedGender ?? "") rides the crest of vibrant waves on a sleek surfboard, surrounded by the golden light of late afternoon. The scene radiates tropical energy, with sun-kissed skin reflecting the glow of golden hour and waves crashing gently along the shore. In the background, colorful palm trees sway in the warm seaside breeze, adding motion and atmosphere to the coastal setting. The overall composition blends confidence, joy, and the freedom of surf culture in a vivid, tropical environment.", imageSize: CGSize(width: 270, height: 150), category: .surfing),
    ImagePreset(image: "https://sdbooth2-production.s3.amazonaws.com/kfaudjghxlmo6qil28b8o5ny77yb", systemPrompt: "A Filipino sks \(Consts.shared.selectedGender ?? "") stands confidently on a sunlit California beach, dressed in vibrant surf gear that reflects the energy of the coast. A surfboard with colorful designs rests beside one leg, while the gaze is fixed thoughtfully on the rolling waves ahead. The backdrop features a clear blue sky and distant palm trees swaying gently in the breeze, capturing the essence of an ideal surf day. The relaxed stance and vivid setting convey a deep connection to the ocean, evoking adventure, warmth, and coastal freedom.", imageSize: CGSize(width: 270, height: 150), category: .surfing),
    ImagePreset(image: "https://sdbooth2-production.s3.amazonaws.com/zhwj8dp4cpsdgtynx7wja84xsy6j", systemPrompt: "A sks \(Consts.shared.selectedGender ?? "") rides the crest of vibrant waves on a sleek surfboard, surrounded by the golden light of late afternoon. The scene radiates tropical energy, with sun-kissed skin reflecting the glow of golden hour and waves crashing gently along the shore. In the background, colorful palm trees sway in the warm seaside breeze, adding motion and atmosphere to the coastal setting. The overall composition blends confidence, joy, and the freedom of surf culture in a vivid, tropical environment.", imageSize: CGSize(width: 270, height: 150), category: .surfing),
    ImagePreset(image: "https://sdbooth2-production.s3.amazonaws.com/4fg80icrwmrjmrsnr5uozpseladx", systemPrompt: "A Filipino sks \(Consts.shared.selectedGender ?? "") stands confidently on a sunlit California beach, dressed in vibrant surf gear that reflects the energy of the coast. A surfboard with colorful designs rests beside one leg, while the gaze is fixed thoughtfully on the rolling waves ahead. The backdrop features a clear blue sky and distant palm trees swaying gently in the breeze, capturing the essence of an ideal surf day. The relaxed stance and vivid setting convey a deep connection to the ocean, evoking adventure, warmth, and coastal freedom.", imageSize: CGSize(width: 270, height: 150), category: .surfing),
    ImagePreset(image: "https://sdbooth2-production.s3.amazonaws.com/k95axftcd4upaw9trbrxm01l973w", systemPrompt: "A sks \(Consts.shared.selectedGender ?? "") rides the crest of vibrant waves on a sleek surfboard, surrounded by the golden light of late afternoon. The scene radiates tropical energy, with sun-kissed skin reflecting the glow of golden hour and waves crashing gently along the shore. In the background, colorful palm trees sway in the warm seaside breeze, adding motion and atmosphere to the coastal setting. The overall composition blends confidence, joy, and the freedom of surf culture in a vivid, tropical environment.", imageSize: CGSize(width: 270, height: 150), category: .surfing),
    ImagePreset(image: "https://sdbooth2-production.s3.amazonaws.com/ellqzgwql4ukq62hlfslkf2b4xpg", systemPrompt: "A Filipino sks \(Consts.shared.selectedGender ?? "") stands confidently on a sunlit California beach, dressed in vibrant surf gear that reflects the energy of the coast. A surfboard with colorful designs rests beside one leg, while the gaze is fixed thoughtfully on the rolling waves ahead. The backdrop features a clear blue sky and distant palm trees swaying gently in the breeze, capturing the essence of an ideal surf day. The relaxed stance and vivid setting convey a deep connection to the ocean, evoking adventure, warmth, and coastal freedom.", imageSize: CGSize(width: 270, height: 150), category: .surfing),
    
    ImagePreset(image: "https://sdbooth2-production.s3.amazonaws.com/fls0m4dl8nv4dkp00z55up5w8u13", systemPrompt: "A sks \(Consts.shared.selectedGender ?? "") with a shredded, aesthetic physique strikes the iconic Zyzz pose, arms raised behind the head in a powerful display. Every muscle group is sharply defined — from deep-cut abs to vascular shoulders and a full, sculpted chest. The dramatic V-taper highlights a narrow waist and wide, chiseled lats. Intense lighting casts deep shadows across the body, emphasizing muscle fibers and vein structure with cinematic clarity. The background is minimal or softly graded, keeping all focus on the peak-conditioned form and confident energy of elite fitness.", category: .gym),
    ImagePreset(image: "https://sdbooth2-production.s3.amazonaws.com/80haapvonuc035siwc3mnliodfj5", systemPrompt: "A sks \(Consts.shared.selectedGender ?? "") is captured in a high-resolution, dynamic fitness portrait, standing in a sleek modern gym environment. Wearing workout clothes, this \(Consts.shared.selectedGender ?? "") displays a muscular and defined physique, with droplets of sweat glistening on the skin under vivid, directional lighting. Weightlifting equipment fills the blurred background, while sharp focus and intense composition highlight raw strength, focus, and determination. The image feels editorial and aspirational — the kind of portrait trending on top fitness and health magazines.", category: .gym),
    ImagePreset(image: "https://sdbooth2-production.s3.amazonaws.com/vlyx9wwwx6z482xwznvyoz61xj69", systemPrompt: "A sks \(Consts.shared.selectedGender ?? "") with a shredded, aesthetic physique strikes the iconic Zyzz pose, arms raised behind the head in a powerful display. Every muscle group is sharply defined — from deep-cut abs to vascular shoulders and a full, sculpted chest. The dramatic V-taper highlights a narrow waist and wide, chiseled lats. Intense lighting casts deep shadows across the body, emphasizing muscle fibers and vein structure with cinematic clarity. The background is minimal or softly graded, keeping all focus on the peak-conditioned form and confident energy of elite fitness.", category: .gym),
    ImagePreset(image: "https://sdbooth2-production.s3.amazonaws.com/pzc08fk7v5mlntibvytb7ize0g1n", systemPrompt: "A sks \(Consts.shared.selectedGender ?? "") is captured in a high-resolution, dynamic fitness portrait, standing in a sleek modern gym environment. Wearing workout clothes, this \(Consts.shared.selectedGender ?? "") displays a muscular and defined physique, with droplets of sweat glistening on the skin under vivid, directional lighting. Weightlifting equipment fills the blurred background, while sharp focus and intense composition highlight raw strength, focus, and determination. The image feels editorial and aspirational — the kind of portrait trending on top fitness and health magazines.", category: .gym),
    ImagePreset(image: "https://sdbooth2-production.s3.amazonaws.com/35hav9vhzw5l7eai3lb3d5x4dcgb", systemPrompt: "A sks \(Consts.shared.selectedGender ?? "") with a shredded, aesthetic physique strikes the iconic Zyzz pose, arms raised behind the head in a powerful display. Every muscle group is sharply defined — from deep-cut abs to vascular shoulders and a full, sculpted chest. The dramatic V-taper highlights a narrow waist and wide, chiseled lats. Intense lighting casts deep shadows across the body, emphasizing muscle fibers and vein structure with cinematic clarity. The background is minimal or softly graded, keeping all focus on the peak-conditioned form and confident energy of elite fitness.", category: .gym),
    ImagePreset(image: "https://sdbooth2-production.s3.amazonaws.com/eea11bfn1v9wss0lvivc0omc0fmq", systemPrompt: "A sks \(Consts.shared.selectedGender ?? "") is captured in a high-resolution, dynamic fitness portrait, standing in a sleek modern gym environment. Wearing workout clothes, this \(Consts.shared.selectedGender ?? "") displays a muscular and defined physique, with droplets of sweat glistening on the skin under vivid, directional lighting. Weightlifting equipment fills the blurred background, while sharp focus and intense composition highlight raw strength, focus, and determination. The image feels editorial and aspirational — the kind of portrait trending on top fitness and health magazines.", category: .gym)
]

let ghibliImages: [URL] = [URL(string: "https://ofiles.kitety.com/ghibli/landingpage/e56036c6-2160-4ef3-bb7d-d189e2eb8c41.webp")!,
    URL(string: "https://www.myimg.ai/static/ghibli-style-ai-generator/ghibli-style-ai-generator-features-hd.webp")!,
    URL(string: "https://images1.dnaindia.com/images/DNA-EN/900x1600/2025/3/29/1743263569718_3.png")!,
    URL(string: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXoyTVkU4l9B5UPJsOYqWRpkAYD89qHOz8fHSEPTIhpkRelxa7mIBfxdS4Ps49d-Voo9Y&usqp=CAU")!,
    URL(string: "https://r2.starryai.com/results/1042960448/3d1f5187-50e5-4d97-a208-e8106e06ecb4.webp")!,
    URL(string: "https://instagram.fkiv7-1.fna.fbcdn.net/v/t51.2885-15/487353781_18356434600181983_5482153751728611888_n.jpg?stp=dst-jpg_e35_tt6&cb=30a688f7-fa102a98&efg=eyJ2ZW5jb2RlX3RhZyI6IkNBUk9VU0VMX0lURU0uaW1hZ2VfdXJsZ2VuLjE0NDB4MjU2MC5zZHIuZjc1NzYxLmRlZmF1bHRfaW1hZ2UifQ&_nc_ht=instagram.fkiv7-1.fna.fbcdn.net&_nc_cat=107&_nc_oc=Q6cZ2QHZqJH-RnkCr7qxAGzZQyW9T0gqi-9CJA0AsGATjFUBkkUMqOvMlMT9gG6nZAZAUcg&_nc_ohc=DDwAijV6FdEQ7kNvwGYSQWd&_nc_gid=t_cvnlPWVotIuuEtrK7-Rw&edm=ALQROFkBAAAA&ccb=7-5&ig_cache_key=MzU5OTA5MTM3NTY5MTE3NTg0OQ%3D%3D.3-ccb7-5-cb30a688f7-fa102a98&oh=00_AfFmulteu-UTaiRmw671aPJoPvDnz0vnynLb_gjOTg1TtQ&oe=680BABDD&_nc_sid=fc8dfb")!
]

let actionFigures: [URL] = [
    URL(string: "https://miro.medium.com/v2/resize:fit:666/1*eXoOtzu0mZoBa6jO5-jrvw.png")!,
    URL(string: "https://media.licdn.com/dms/image/v2/D4E22AQGG2KgpuvHbQQ/feedshare-shrink_800/B4EZYHswJVGgAo-/0/1743885897431?e=2147483647&v=beta&t=QLFK5mHp33bks4Xc5JzEdRCJpZ8Dq-l-Y4Ssh8mVeYk")!,
    URL(string: "https://s.yimg.com/ny/api/res/1.2/5qPqtcgNazZv11LtoNCH2Q--/YXBwaWQ9aGlnaGxhbmRlcjt3PTk2MDtoPTE0NDA-/https://media.zenfs.com/en/whtm_articles_902/27b3b98b21064e3aa4898f41feb38a9f")!,
    URL(string: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSxpZRGBlgjUN_Q1oTvrw83Nq0bPlLQ_YZ8S7j_VXOU2jCCTfJWEpYSLg7yPnDMfA8Lpn0&usqp=CAU")!,
    URL(string: "https://plugins-media.makeupar.com/smb/story/2025-04-08/ae9e473f-96db-474c-8a9b-975a86f6c346.png")!
]
